export const CONNEXION = 'CONNEXION'
export const LOGOUT = 'LOGOUT'
export const ADMIN = 'ADMIN'
export const USER = 'USER'
export const USERS = 'USERS'
export const PRESTATION= 'PRESTATION'
export const PRODUIT= 'PRODUIT'